### ISSUE TITLE
Peds/npc police do not pull me over 

### ISSUE THREAD

**Issue by Unorthodox23** [BirddMann/pull-me-over#1]
my issue is related to npc police do not chase me if i speed or do anything if i fire my gun ,kill someone or hit there car then i get wanted stars but as far as getting pulled over seems i cant get that part to work . im using esx seems that they disabled most scenarios and gang peds so police isnt as active in the streets anymore.

**Comment by BirddMann** [comment]
Thanks for downloading the mod

The speeding function will fail if the exports for mythic_notify can't be found
If this is working you will see 'Radar Detected x/65 mph' flash when driving in front of an NPC cop, either in red or blue

```
exports['mythic_notify']:SendAlert("inform", 'Radar Detected - '..mph..' / 65 mph', 1500)
```
Do you see these notifications at all?

**Comment by Unorthodox23** [comment]
no i do not get any notifications is there a correct way to install mythic_notify ? all i did was ensure it in my cfg

**Comment by BirddMann** [comment]
Need to download it from github or cfx.re and place it into /resources - this should do it https://github.com/yordi-a/mythic_notify

**Comment by Unorthodox23** [comment]
yea im not sure why its not working for me then because cops respond like normal but no speeding notifications at all

**Comment by Unorthodox23** [comment]
ok i got it to work 2 questions is there a way to make them pull you over for other violations like running red light or reckless driving second question how do i make the cop stay by my car a tad bit longer he walks back to his caar so quickly lol

**Comment by Unorthodox23** [comment]
Hey man last two questions mod has been working fantastic one bug I notice is if a player drives toooo fast and lets say I make a turn around on freeway the cop gets confused/lost and never pulls up so when I pull off wanted level starts maybe in future you can make it where they spawn behind you after a certain amount of time of sitting and waiting just throwing that out there everything else runs great with this mod .
Second question off topic I notice with your npc police script I get close to no truck and trailers on the road is that popcycle ? Cause I tried moving veh_hauler to more zones in your popcycle but still no trucks with trailers attached appearing in traffic only with the popcycle taken out and even when I do that I see a truck like that every once in awhile seems like the rarest cars on the server at this point lol

**Comment by BirddMann** [comment]
That would be popcycle yes, I have industrial vehicles tuned down in most places.

Low/mid/high groups get most priority

You can add any desired vehicles into popgroups under low/mid/high, pounder/mule/packer... etc

I will look into the spawn behind function also

ty much
