### ISSUE TITLE
NPC not pulling me over / no notifications

### ISSUE THREAD

**Issue by Geckomacabre** [BirddMann/pull-me-over#3]
Firstly I updated the server and client .lua according to this https://documentation.esx-framework.org/tutorials/tutorials-esx/sharedevent/
I did this because I wasn't sure if that was the reason it wasn't working.
My game version is 2545
My es_extended has wanted level enabled, I was using CalmNPC but removed it because I didn't know if it was causing conflicts.
I am using mythic notify, I also added the npc_police 

Ive looked at the closed issue and noticed this 

`exports['mythic_notify']:SendAlert("inform", 'Radar Detected - '..mph..' / 65 mph', 1500)`

Does this need to be added to the fxmanifest.lua or is it already baked into the code?

Is there something I'm not doing or need to add or remove?

Attached is a clip of me trying to trigger a response
Also my servers mod list
https://youtu.be/AMlW-5UED8E

![20230516113617_1](https://github.com/BirddMann/pull-me-over/assets/91030858/4e9067d4-fe21-4537-8046-9c091856b74d)
![20230516113635_1](https://github.com/BirddMann/pull-me-over/assets/91030858/de8cf028-ad1a-4b79-bd16-45ef2efda07d)
![20230516113641_1](https://github.com/BirddMann/pull-me-over/assets/91030858/8a90cd38-193d-481e-9d05-bbe96f75cfe3)
![20230516113647_1](https://github.com/BirddMann/pull-me-over/assets/91030858/e7fb4302-f961-48f1-9151-f48161754700)

**Comment by BirddMann** [comment]
Thanks for downloading the mod

The speeding function will fail if the exports for mythic_notify can't be found, or if a server callback/trigger fails
If this is working you will see 'Radar Detected x/65 mph' flash at the top of the screen when driving in front of an NPC cop, either in red or blue

If you don't see this, that is probably the issue
For the Mythic Notify lines, you'll need to download that resource from github or cfx.re and place it into /resources - this should do it [JayMontana36/mythic_notify: A simple FiveM notification resource 9](https://github.com/JayMontana36/mythic_notify)

Start that resource, and check for output in the F8 console when passing a cop, any errors will show up there, also check the server console output for server sided errors, paste here if found.

Thanks.
Bird

**Comment by BirddMann** [comment]
Also the video linked showed firing at officers, it takes a few more commands/scripts to get that going properly, this script is just for when driving around.  my [warrant](https://github.com/BirddMann/warrant) script does all the work, but you'd need to comb all other lua files for police response and dispatch, also relationships that may be applying to all peds (need to exclude pedtype 6 from that)

Thanks, hope this helps,
Bird

**Comment by Unorthodox23** [comment]
When you say combine all lua are you saying I can merge both pull me and warrant together?

**Comment by BirddMann** [comment]
you can use both warrant and pullmeover in conjunction, but sorry I was referring to combing all your other lua files, I mean ALL lol

I search for all *.lua files in resources and open all the files in notepad++ at once, then use the search to find in all documents

Best way to track something down, takes time but works

**Comment by Unorthodox23** [comment]
Ohhhhhhh lol Mybad and why don’t you use visual studio code ? That way your not opening every single file everytime less and cleaner working area imo

**Comment by Unorthodox23** [comment]
can you make a version with pull me over and warrent together ? or how would i do it?

**Comment by BirddMann** [comment]
personal preference. you'd need to combine the client, server, and manifest files. I can do that when I get some time.
